[package]
name = "golem-db"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4.26"
diesel = { version = "2.1.5", features = ["sqlite", "chrono"] }
diesel_migrations = "2.1.0"
retronomicon-dto = "0.2.3"
strum = "0.25.0"
tracing = "0.1.37"
