[target.armv7-unknown-linux-gnueabihf]
# TODO: figure out how to install clang and use it.
# rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]

#linker = "/usr/bin/clang"
#rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]

#rustflags = ["-C", "target-cpu=native"]
rustflags = ["-C", "target-feature=+neon"]
